#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Epirb.Resource", IsApplication=true)]

namespace Epirb
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Mindscape.Raygun4Net.Xamarin.Android.Resource.String.library_name = global::Epirb.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int black = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int red_button = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int BackButton = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int CancelButton = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int ConcatText = 2131165198;
			
			// aapt resource value: 0x7f070009
			public const int NameText = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int NotesText = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int SaveButton = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int VesselDetailList = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int contacts = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int edit_my_info_button = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int get_help_button = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int lstItemVesselDetail = 2131165197;
			
			// aapt resource value: 0x7f070007
			public const int sms_message_text1 = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int spacer = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int spacer2 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int textHeader = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Edit = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int VesselDetailDetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int VesselDetailListItem = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Mono_Android_Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int button_text = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
